### ISSUE TITLE
Use f-strings

### ISSUE THREAD

**Issue by ghost** [redd4ford/laboratory-works-Python-2020#5]
I happened to stumble upon your project and decided to look at it's code. It's decently well-written other than the fact that you used concatenation instead of f-strings. For example, in [hotel.py](https://github.com/redd4ford/iot-Python/blob/master/lab-1-python-class-usage/src/hotel.py)

```py
def __del__(self):
    print('deleted ' + self.__class__.__name__)
```
is the exact same as 
```py
def __del__(self):
    print(f'deleted {self.__class__.__name__}')
```

But as you can tell, using f-strings is far more clean. 
[<img src="https://user-images.githubusercontent.com/57762641/187449429-8f24b855-6546-45cd-b9d6-3949535b8c5e.png">](https://github.com/redd4ford/iot-Python/blob/1e03255483a8c86d71b567b8ce334335164f77bf/lab-1-python-class-usage/src/hotel.py#L17)

it makes things like these easier to read.

**Comment by redd4ford** [comment]
Hey, thanks for your issue!
This was a repository from my junior year of university, and I decided to keep it that way to track my programming journey.

In fact, f-strings are not only easier to read, they're also faster than any other string formatting method, since they're a part of the language's grammar and syntax. And there are lots of cool features, e.g. you can put lambda expressions there, format datetime, call `__repr__` implementation, center the text, split numbers, add leading zeros to numbers etc. Long story short, that indeed is a cool concept to work with.

**Comment by ghost** [comment]
I knew f-strings were really cool, but i didn't know that they're actually faster! i guess you learn something new every day :)
